name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check & Lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Check
        run: cargo check --verbose
      - name: Format
        run: cargo fmt
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-format code"
      - name: Clippy
        run: cargo clippy -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Run tests
        run: cargo test --verbose

  wasm:
    name: wasm32 Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown
      - name: Check (no default features)
        run: cargo check --target wasm32-unknown-unknown --no-default-features
      - name: Check (default features)
        run: cargo check --target wasm32-unknown-unknown

  dry-run-publish:
    name: Dry Run Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Check version consistency
        run: |
            # We only dry-run zabi-derive because zabi-rs depends on it.
            cargo publish --dry-run --manifest-path zabi-derive/Cargo.toml
