[package]
name = "zabi-derive"
version = "0.1.1"
edition = "2021"
description = "Procedural macros for zabi-rs"
license = "MIT"
repository = "https://github.com/smallyunet/zabi-rs"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["full", "derive"] }
proc-macro2 = "1.0"
